MCU = atmega32u4
BOOTLOADER = caterina
LTO_ENABLE = yes

SPLIT_KEYBOARD = yes

OLED_ENABLE = no
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

BACKLIGHT_ENABLE = no

# RGB underglow
RGBLIGHT_ENABLE = yes
# Per key RGB
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = ws2812

LOCAL_GLCDFONT = yes

# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
