MCU = atmega32u4
BOOTLOADER = caterina

# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306     # Enables the use of OLED displays
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no

SPLIT_KEYBOARD = yes
