MCU = atmega32u4
BOOTLOADER = caterina
LTO_ENABLE = yes

SPLIT_KEYBOARD = yes

OLED_ENABLE = yes
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no

LOCAL_GLCDFONT = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
